# Copyright 2016, Sandvine Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Creating OpenStack Endpoint
  environment: openstack_env
  command: "{{item}}"
  with_items:
  - openstack endpoint create --region "{{region}}" --publicurl http://{{public_addr}}:5000/v2.0 --internalurl http://{{controller_addr}}:5000/v2.0 --adminurl http://{{controller_addr}}:35357/v2.0 identity
  - openstack endpoint create --region "{{region}}" --publicurl http://{{public_addr}}:5000/v3 --internalurl http://{{controller_addr}}:5000/v3 --adminurl http://{{controller_addr}}:35357/v3 identity
  - openstack endpoint create --region "{{region}}" --publicurl http://{{public_addr}}:9292 --internalurl http://{{controller_addr}}:9292 --adminurl http://{{controller_addr}}:9292 image
  - openstack endpoint create --region "{{region}}" --publicurl http://{{public_addr}}:8774/v2/%\(tenant_id\)s --internalurl http://{{controller_addr}}:8774/v2/%\(tenant_id\)s --adminurl http://{{controller_addr}}:8774/v2/%\(tenant_id\)s compute
  - openstack endpoint create --region "{{region}}" --publicurl http://{{public_addr}}:8774/v3 --internalurl http://{{controller_addr}}:8774/v3 --adminurl http://{{controller_addr}}:8774/v3 computev3
  - openstack endpoint create --region "{{region}}" --publicurl http://{{public_addr}}:9696 --internalurl http://{{controller_addr}}:9696 --adminurl http://{{controller_addr}}:9696 network
  - openstack endpoint create --region "{{region}}" --publicurl http://{{public_addr}}:8776/v2/%\(tenant_id\)s --internalurl http://{{controller_addr}}:8776/v2/%\(tenant_id\)s --adminurl http://{{controller_addr}}:8776/v2/%\(tenant_id\)s volume
  - openstack endpoint create --region "{{region}}" --publicurl http://{{public_addr}}:8776/v2/%\(tenant_id\)s --internalurl http://{{controller_addr}}:8776/v2/%\(tenant_id\)s --adminurl http://{{controller_addr}}:8776/v2/%\(tenant_id\)s volumev2
  - openstack endpoint create --region "{{region}}" --publicurl http://{{public_addr}}:8004/v1/%\(tenant_id\)s --internalurl http://{{controller_addr}}:8004/v1/%\(tenant_id\)s --adminurl http://{{controller_addr}}:8004/v1/%\(tenant_id\)s orchestration
  - openstack endpoint create --region "{{region}}" --publicurl http://{{public_addr}}:8000/v1 --internalurl http://{{controller_addr}}:8000/v1 --adminurl http://{{controller_addr}}:8000/v1 cloudformation
  - openstack endpoint create --region "{{region}}" --publicurl http://{{public_addr}}:8773/services/Cloud --internalurl http://{{controller_addr}}:8773/services/Cloud --adminurl http://{{controller_addr}}:8773/services/Admin ec2
  - openstack endpoint create --region "{{region}}" --publicurl http://{{public_addr}}:8080/v1/AUTH_%\(tenant_id\)s --internalurl http://{{controller_addr}}:8080/v1/AUTH_%\(tenant_id\)s --adminurl http://{{controller_addr}}:8080/v1 swift
  - openstack endpoint create --region "{{region}}" --publicurl http://{{public_addr}}:8777 --internalurl http://{{controller_addr}}:8777 --adminurl http://{{controller_addr}}:8777 metering
  when: keystone_started|changed
  register: openstack_endpoint_ready
