# Copyright 2016, Sandvine Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Installing MySQL Server
  action: apt pkg={{item}} state=installed
  with_items:
    - mysql-server
  register: mysql_installed

- name: Updating my.cnf
  copy: src=my.cnf
        dest=/etc/mysql/my.cnf
        owner=root
        group=root
        mode=0644
        backup=yes
  when: mysql_installed|changed
  register: my_cnf_updated

- name: Restarting MySQL
  service: name=mysql state=restarted
  when: my_cnf_updated|changed
  register: mysql_ready

- name: Creating OpenStack MySQL databases
  mysql_db: name={{item.db_name}} state=present
  when: mysql_ready|changed
  with_items: mysql_databases
  
- name: Creating OpenStack MySQL users 
  mysql_user:
    host="{{item.db_host}}"
    name="{{item.db_user}}"
    password="{{item.db_pass}}"
    priv="{{item.db_name}}.*:ALL,GRANT"
    state=present
  when: mysql_ready|changed
  with_items: mysql_databases
